name: Build Dylib

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          curl -L -o sdk.tar.xz "https://github.com/theos/sdks/releases/download/2024-10-27/iPhoneOS17.5.sdk.tar.xz"
          file sdk.tar.xz
          tar -xf sdk.tar.xz -C $THEOS/sdks

      - name: Build dylib
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          make

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: IshinRedirect.dylib
          path: .theos/obj/debug/IshinRedirect.dylib
          if-no-files-found: error
